AUTO_ADD_GLOBAL_DEFINE_BY_NAME = MTK_LCA_SUPPORT MTK_WAPI_SUPPORT MTK_BT_SUPPORT MTK_CAMERA_APP_3DHW_SUPPORT MTK_QVGA_LANDSCAPE_SUPPORT MTK_WLANBT_SINGLEANT MTK_FM_TX_SUPPORT MTK_VT3G324M_SUPPORT MTK_M4U_SUPPORT MTK_MATV_ANALOG_SUPPORT MTK_WLAN_SUPPORT MTK_BT_21_SUPPORT MTK_BT_30_SUPPORT MTK_BT_40_SUPPORT MTK_BT_FM_OVER_BT_VIA_CONTROLLER MTK_BT_PROFILE_OPP MTK_BT_PROFILE_SIMAP MTK_BT_PROFILE_PRXM MTK_BT_PROFILE_PRXR MTK_BT_PROFILE_HIDH MTK_BT_PROFILE_FTP MTK_BT_PROFILE_PBAP MTK_BT_PROFILE_MANAGER MTK_BT_PROFILE_BPP MTK_BT_PROFILE_BIP MTK_BT_PROFILE_DUN MTK_BT_PROFILE_PAN MTK_BT_PROFILE_HFP MTK_BT_PROFILE_A2DP MTK_BT_PROFILE_AVRCP MTK_BT_PROFILE_AVRCP14 MTK_BT_PROFILE_TIMEC MTK_BT_PROFILE_TIMES MTK_BT_PROFILE_MAPS MTK_BT_PROFILE_MAPC MTK_BT_PROFILE_SPP MTK_FM_SHORT_ANTENNA_SUPPORT MTK_WB_SPEECH_SUPPORT HAVE_AWBENCODE_FEATURE HAVE_AACENCODE_FEATURE MTK_DUAL_MIC_SUPPORT MTK_WIFI_HOTSPOT_SUPPORT MTK_CTA_SUPPORT MTK_FM_SUPPORT MTK_GPS_SUPPORT MTK_DSPIRDBG MTK_AUTO_DETECT_ACCELEROMETER MTK_AUTO_DETECT_MAGNETOMETER HAVE_XLOG_FEATURE MTK_MAV_SUPPORT MTK_CAMERA_BSP_SUPPORT MTK_AUTORAMA_SUPPORT MTK_IPV6_SUPPORT MTK_MULTI_STORAGE_SUPPORT MTK_FM_RECORDING_SUPPORT MTK_USES_HD_VIDEO MTK_NFC_SUPPORT MTK_THEMEMANAGER_APP MTK_BRAZIL_CUSTOMIZATION MTK_BRAZIL_CUSTOMIZATION_CLARO MTK_BRAZIL_CUSTOMIZATION_VIVO MTK_RMVB_PLAYBACK_SUPPORT MTK_ASF_PLAYBACK_SUPPORT MTK_HDMI_SUPPORT MODEM_UMTS_TDD128_MODE MTK_EAP_SIM_AKA MTK_FACEBEAUTY_SUPPORT MTK_FM_RX_SUPPORT MTK_TB_DEBUG_SUPPORT MTK_FAN5405_SUPPORT MTK_COMBO_SUPPORT MTK_CAMCORDER_PROFILE_MID_MP4 MTK_DISPLAY_HIGH_RESOLUTION MTK_FD_SUPPORT MTK_MASS_STORAGE MTK_FM_50KHZ_SUPPORT

AUTO_ADD_GLOBAL_DEFINE_BY_VALUE = MTK_PLATFORM MTK_FM_CHIP MTK_BT_CHIP CUSTOM_KERNEL_IMGSENSOR CUSTOM_KERNEL_LENS CUSTOM_KERNEL_FLASHLIGHT MTK_ATV_CHIP MTK_IME_INPUT_ENGINE MTK_IME_HANDWRITING_ENGINE MTK_MODEM_SUPPORT CUSTOM_KERNEL_LCM MTK_FM_TX_AUDIO MTK_FM_RX_AUDIO MTK_COMBO_CHIP

AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE = MTK_LCM_PHYSICAL_ROTATION MTK_SHARE_MODEM_SUPPORT MTK_SHARE_MODEM_CURRENT

#
# MTK Build System
#
BUILD_KERNEL = no
	# default settings: yes for target; else no (e.g. emulator)
	# candidate settings: yes; no
	# used for MTK build system

BUILD_PRELOADER = no
	# default settings: yes for target; else no (e.g. emulator)
	# candidate settings: yes; no
	# used for MTK build system

BUILD_UBOOT = no
	# default settings: yes for target; else no (e.g. emulator)
	# candidate settings: yes; no
	# used for MTK build system

# api: Create MTK SDK API package only (e.g. mtk_sdk_api_addon-10.1.zip)
# toolset: Create MTK SDK Toolset package only (e.g. mtk_sdk_toolset-1.0.zip)
# all: Create both MTK SDK API and Toolset packages
BUILD_MTK_SDK = all

#
# Customize for PRELOADER
#
CUSTOM_PRELOADER_CUSTOM = 


#
# Customize for HAL
#
CUSTOM_HAL_AUDIOFLINGER = audio

CUSTOM_HAL_BLUETOOTH = bluetooth

CUSTOM_HAL_CAMERA = camera

CUSTOM_HAL_EEPROM = dummy_eeprom

CUSTOM_HAL_FLASHLIGHT = dummy_flashlight


CUSTOM_HAL_LENS = dummy_lens

CUSTOM_HAL_IMGSENSOR = ov5642_raw


#
# Customize for Kernel
#
CUSTOM_KERNEL_CAMERA = camera

CUSTOM_KERNEL_ACCELEROMETER = 

CUSTOM_KERNEL_CORE = 
	# default settings: src
	# candidate settings: src
	# board configuation. .

CUSTOM_KERNEL_DCT = 

CUSTOM_KERNEL_EEPROM = dummy_eeprom

CUSTOM_KERNEL_FLASHLIGHT = dummy_flashlight

CUSTOM_KERNEL_JOGBALL = 

CUSTOM_KERNEL_KPD = 
	# default settings: kpd
	# candidate settings: kpd
	# For Keypad

CUSTOM_KERNEL_LCM = 

CUSTOM_KERNEL_LEDS = 

CUSTOM_KERNEL_LENS = dummy_lens

CUSTOM_KERNEL_MAGNETOMETER = 

CUSTOM_KERNEL_OFN =

CUSTOM_KERNEL_IMGSENSOR = ov5642_raw

CUSTOM_KERNEL_SOUND = 

CUSTOM_KERNEL_TOUCHPANEL = 
	# default settings: generic
	# candidate settings: generic;eeti_pcap7200
	# select the panel used by certain project.

CUSTOM_KERNEL_USB = 

#CUSTOM_KERNEL_WIFI = mt592x
CUSTOM_KERNEL_WIFI = 


#
# Misc
#
EVB = no
	# default settings: yes for evb; else no
	# candidate settings: yes/no
	# For EVB used

GEMINI = yes
	# default settings: no
	# candidate settings: yes/no
	# For gemini;currently no projects is set gemini on

MTK_GEMINI_ENHANCEMENT = yes

OPTR_SPEC_SEG_DEF = NONE
	# default settings: NONE
#
# Option to turn on/off default RILD for emulator
#
GOOGLE_RELEASE_RIL = no

#
# MTK Specified Feature
#
HAVE_AEE_FEATURE = no

HAVE_APPC_FEATURE = yes

HAVE_MATV_FEATURE = no
#
# MTK Chip
#
MTK_BT_CHIP = MTK_MT6611
	# candidate settings: MTK_MT6611/MTK_MT6612/MTK_MT6616

MTK_CHIP_VER = S01
	# default settings: S01
	# candidate settings: S01
	# S01 for MT6516

MTK_FM_CHIP = AR1000_FM
	# candidate settings: AR1000_FM/MT6616_E3_FM

MTK_ATV_CHIP = MTK_MT5192

MTK_PLATFORM =
	# default settings: MT6516
	# candidate settings: MT6516
	# MT6516 is available

#
# MTK APP
#
MTK_GALLERY3D_APP = no

MTK_YGPS_APP = yes

MTK_INPUTMETHOD_PINYINIME_APP = no

MTK_GALLERY_APP = yes

MTK_LIVEWALLPAPER_APP = no

MTK_ACWFDIALOG_APP = yes

MTK_ENGINEERMODE_APP = no

MTK_LAUNCHERPLUS_APP = yes

MTK_SOUNDRECORDER_APP = no

MTK_DM_APP = no

MTK_ANDROIDFACTORYMODE_APP = yes

MTK_VIDEOWIDGET_APP = no

#
# MTK SUPPORT
#

MTK_EMULATOR_SUPPORT = yes

MTK_CAMERA_APP = no

MTK_TVOUT_SUPPORT = no

MTK_SNS_SUPPORT = yes

MTK_LCA_SUPPORT = no

MTK_WAPI_SUPPORT = no

MTK_WLAN_SUPPORT = yes

MTK_BT_SUPPORT = no

MTK_CAMERA_APP_3DHW_SUPPORT = yes

MTK_SMS_NATIONAL_LANGUAGE_SUPPORT = no

MTK_SMS_TURKISH_TABLE_ALWAYS_SUPPORT = yes

MTK_WAPPUSH_SUPPORT = yes

MTK_WLANBT_SINGLEANT = no

MTK_QVGA_LANDSCAPE_SUPPORT = no

MTK_LCM_PHYSICAL_ROTATION = 0
  # set this value as 90 if the lcm is physically rotated on the device

MTK_FM_TX_SUPPORT = no

MTK_SCREEN_OFF_WIFI_OFF = no

MTK_VT3G324M_SUPPORT = no

MTK_M4U_SUPPORT = no

MTK_MT519X_FM_SUPPORT = no

MTK_LOCKSCREEN_TYPE = 2
  # default=1, slide=2

MTK_MATV_ANALOG_SUPPORT = no
   # For I2S, use: no
   # For Audio Line-in, use: yes

# add for IME feature
MTK_IME_HANDWRITING_ENGINE = none
MTK_IME_INPUT_ENGINE = none

MTK_IME_SUPPORT = no

MTK_IME_ENGLISH_SUPPORT = no

MTK_IME_PINYIN_SUPPORT = no

MTK_IME_STROKE_SUPPORT = no

MTK_IME_ZHUYIN_SUPPORT = no

MTK_IME_HANDWRITING_SUPPORT = no

MTK_HEADSET_ICON_SUPPORT = no

MTK_OMA_DOWNLOAD_SUPPORT = yes

MTK_SMARTSWITCH_SUPPORT = no

MTK_IPO_SUPPORT = no

RESOURCE_OVERLAY_SUPPORT = 

MTK_OMACP_SUPPORT = no


MTK_BT_30_HS_SUPPORT = no

MTK_WCDMA_SUPPORT = no

TARGET_ARCH_VARIANT =

MTK_GOOGLEOTA_SUPPORT = no

####config BT feature###########
# please do not modify these options

MTK_BT_21_SUPPORT = no

MTK_BT_30_SUPPORT = no

MTK_BT_40_SUPPORT = no

MTK_BT_FM_OVER_BT_VIA_CONTROLLER = no

MTK_BT_PROFILE_OPP = no

MTK_BT_PROFILE_SIMAP = no

MTK_BT_PROFILE_PRXM = no

MTK_BT_PROFILE_PRXR = no

MTK_BT_PROFILE_HIDH = no

MTK_BT_PROFILE_FTP = no

MTK_BT_PROFILE_PBAP = no

MTK_BT_PROFILE_MANAGER = no

MTK_BT_PROFILE_BPP = no

MTK_BT_PROFILE_BIP = no

MTK_BT_PROFILE_DUN = no

MTK_BT_PROFILE_PAN = no

MTK_BT_PROFILE_HFP = no

MTK_BT_PROFILE_A2DP = no

MTK_BT_PROFILE_AVRCP = no

MTK_BT_PROFILE_AVRCP14 = no

MTK_BT_PROFILE_TIMEC = no

MTK_BT_PROFILE_TIMES = no

MTK_BT_PROFILE_MAPS = no

MTK_BT_PROFILE_MAPC = no

MTK_BT_PROFILE_SPP = no

####config BT feature end ####

MTK_WIFI_P2P_SUPPORT = no

MTK_FM_SHORT_ANTENNA_SUPPORT = no

MTK_MDLOGGER_SUPPORT = no

MTK_SNS_KAIXIN_APP = yes

MTK_SNS_RENREN_APP = yes

MTK_SNS_FACEBOOK_APP = yes

MTK_SNS_FLICKR_APP = yes

MTK_SNS_TWITTER_APP = yes

MTK_IME_FRENCH_SUPPORT = no

MTK_IME_GERMAN_SUPPORT = no

MTK_IME_SPANISH_SUPPORT = no

MTK_IME_ITALIAN_SUPPORT = no

MTK_IME_PORTUGUESE_SUPPORT = no

MTK_IME_TURKISH_SUPPORT = no

MTK_IME_MALAY_SUPPORT = no

MTK_IME_HINDI_SUPPORT = no

MTK_IME_ARABIC_SUPPORT = no

MTK_IME_THAI_SUPPORT = no

MTK_IME_VIETNAM_SUPPORT = no

MTK_IME_INDONESIAN_SUPPORT = no

MTK_FILEMANAGER_APP = yes

MTK_TTY_SUPPORT = no

MTK_WPA2PSK_SUPPORT = no

MTK_WB_SPEECH_SUPPORT = yes

HAVE_AWBENCODE_FEATURE = no

MTK_NAND_PAGE_SIZE = 2K

HAVE_AACENCODE_FEATURE = no

# Enable dual mic support
MTK_DUAL_MIC_SUPPORT = no


MTK_APKINSTALLER_APP = no

MTK_SEARCH_DB_SUPPORT = yes

MTK_DIALER_SEARCH_SUPPORT = yes


MTK_SMSREG_APP = no

MTK_RELEASE_PACKAGE = rel_customer_basic

MTK_MFV_MPEG4_EXTRA = no

MTK_VLW_APP = no

MTK_FM_SUPPORT = no

MTK_MODEM_SUPPORT =

MTK_AGPS_APP = no

MTK_GPS_SUPPORT = no


MTK_RESOURCE_OPTIMIZATION = 

MTK_VIDEOPLAYER_APP = no

MTK_INTERNAL = no

MTK_INTERNAL_LANG_SET = no

MTK_CALENDAR_IMPORTER_APP = no

CUSTOM_HAL_ANT = mt6620_ant_m3

MTK_IME_RUSSIAN_SUPPORT = no

MTK_DM_ENTRY_DISPLAY = no

MTK_DSPIRDBG = no



MTK_FOTA_SUPPORT = no

MTK_PHONE_VT_MM_RINGTONE = no

MTK_PHONE_VT_VOICE_ANSWER = no

MTK_PHONE_VOICE_RECORDING = yes

MTK_MUSIC_LRC_SUPPORT = no

MTK_FD_SUPPORT = no

MTK_SNS_SINAWEIBO_APP = yes


MTK_AUTO_DETECT_ACCELEROMETER = no


MTK_AUTO_DETECT_MAGNETOMETER = no


MTK_DRM_APP = yes


MTK_THEMEMANAGER_APP = yes


HAVE_XLOG_FEATURE = yes


MTK_YMCAPROP_SUPPORT = no

MTK_SMS_FILTER_SUPPORT = no


MTK_RTP_OVER_RTSP_SUPPORT = no

MTK_SPECIAL_FACTORY_RESET = no

MTK_MAV_SUPPORT = yes

MTK_CAMERA_BSP_SUPPORT = yes

MTK_DITHERING_SUPPORT = yes

MTK_WEATHER_PROVIDER_APP = yes

MTK_GEMINI_3G_SWITCH = no

MTK_LOG2SERVER_APP = no

MTK_AUTORAMA_SUPPORT = no


MTK_VIDEOPLAYER2_APP = yes


MTK_IPV6_SUPPORT = yes


MTK_USES_STAGEFRIGHT_DEFAULT_CODE = yes


MTK_MULTI_STORAGE_SUPPORT = no


MTK_SHARE_MODEM_SUPPORT = 2


MTK_SHARE_MODEM_CURRENT = 2





MTK_EAP_SIM_AKA = no

MTK_NFC_SUPPORT = no

MTK_NEW_IPTABLES_SUPPORT = yes


MTK_ASD_SUPPORT = no


MTK_EMMC_SUPPORT = no


MTK_FM_RECORDING_SUPPORT = no


MTK_USES_HD_VIDEO = no


MTK_AVI_PLAYBACK_SUPPORT = no


MTK_SIGNATURE_CUSTOMIZATION = no


MTK_WML_SUPPORT = no

MTK_FLV_PLAYBACK_SUPPORT = no

MTK_PRODUCT_LOCALES = en_US es_ES zh_CN zh_TW ru_RU pt_BR fr_FR de_DE tr_TR it_IT in_ID ms_MY vi_VN ar_EG th_TH pt_PT nl_NL ldpi hdpi mdpi


MTK_TB_APP_LANDSCAPE_SUPPORT = no


MTK_BRAZIL_CUSTOMIZATION_TIM = no

HAVE_VORBISENC_FEATURE = no

MTK_FD_FORCE_REL_SUPPORT = no

MTK_AUDIO_APE_SUPPORT = no


MTK_BRAZIL_CUSTOMIZATION = no

MTK_BRAZIL_CUSTOMIZATION_CLARO = no


MTK_BRAZIL_CUSTOMIZATION_VIVO = no


MTK_RMVB_PLAYBACK_SUPPORT = no


MTK_ASF_PLAYBACK_SUPPORT = no


MTK_WEATHER_WIDGET_APP = yes

MTK_WORLD_CLOCK_WIDGET_APP = yes

# Disable HWUI on emulator
USE_OPENGL_RENDERER = false






MODEM_UMTS_TDD128_MODE = no


MTK_ENGINEERMODE_INTERNAL_APP = no

MTK_FOTA_ENTRY = no

MTK_SCOMO_ENTRY = no






MTK_OGM_PLAYBACK_SUPPORT = no

MTK_MTKPS_PLAYBACK_SUPPORT = no


MTK_RAT_WCDMA_PREFERRED = yes


MTK_FACEBEAUTY_SUPPORT = yes



MTK_FM_RX_SUPPORT = yes


MTK_FM_TX_AUDIO = FM_DIGITAL_OUTPUT


MTK_FM_RX_AUDIO = FM_DIGITAL_INPUT

MTK_SEND_RR_SUPPORT = yes

MTK_DEFAULT_DATA_OFF = no

DEFAULT_INPUT_METHOD = com.sohu.inputmethod.sogou.SogouIME

DEFAULT_LATIN_IME_LANGUAGES = en_US

CUSTOM_SEC_SIGNTOOL_SUPPORT = no

CUSTOM_SEC_AUTH_SUPPORT = no

MTK_SEC_SECRO_AC_SUPPORT = no

MTK_TABLET_PLATFORM = no

MTK_TB_APP_CALL_FORCE_SPEAKER_ON = no

MTK_TB_DEBUG_SUPPORT = no


MTK_FAN5405_SUPPORT = no


MTK_COMBO_SUPPORT = no



MTK_CAMCORDER_PROFILE_MID_MP4 = no


MTK_DISPLAY_HIGH_RESOLUTION = no

